name: custom_uui_design
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  go_router: ^15.2.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/travel/